/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as KeepRouteImport } from './routes/keep'
import { Route as KeptIdRouteImport } from './routes/kept.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepRoute = KeepRouteImport.update({
  id: '/keep',
  path: '/keep',
  getParentRoute: () => rootRouteImport,
} as any)
const KeptIdRoute = KeptIdRouteImport.update({
  id: '/kept/$id',
  path: '/kept/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/keep': typeof KeepRoute
  '/kept/$id': typeof KeptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/keep': typeof KeepRoute
  '/kept/$id': typeof KeptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/keep': typeof KeepRoute
  '/kept/$id': typeof KeptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/keep' | '/kept/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/keep' | '/kept/$id'
  id: '__root__' | '/' | '/calendar' | '/keep' | '/kept/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  KeepRoute: typeof KeepRoute
  KeptIdRoute: typeof KeptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keep': {
      id: '/keep'
      path: '/keep'
      fullPath: '/keep'
      preLoaderRoute: typeof KeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kept/$id': {
      id: '/kept/$id'
      path: '/kept/$id'
      fullPath: '/kept/$id'
      preLoaderRoute: typeof KeptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  KeepRoute: KeepRoute,
  KeptIdRoute: KeptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
